thias/puppet-nagios

manifests/params.pp

Debian case would not work with Ubuntu

Adds Ubuntu case to params.pp

---

files/messages.nrpe
lib/facter/nagios_postgres.rb
manifests/check/postgres.pp
manifests/check/postgres/mode.pp
manifests/client.pp
manifests/server.pp
templates/plugins/check_postgres-sudoers.erb

More actions (modes) to be added in the future!

Add support for postgres

---

manifests/client.pp
manifests/params.pp

Simple change to get the correct directory.

Support ppc64 architecture

---

manifests/client.pp

Added an option to client.pp to disable the default checks.

added option to disable default checks

---

manifests/server.pp
templates/nagios.cfg.erb

This is in response to @dobrerazvan submitting a PR [against my fork](https://github.com/zxjinn/puppet-nagios/pull/1)

allow nagios.cfg timeouts to be customized

---

lib/facter/nagios_ipaddress6.rb

Make nagios_ipaddrress6 fact work with newer facter

---

lib/facter/nagios_ipaddress6.rb

Ruby 1.8.x doesn't like .method calls

---

lib/facter/nagios_pci.rb
manifests/check/hpsa.pp
manifests/client.pp
manifests/server.pp
templates/plugins/README
templates/plugins/check_hpsa
templates/plugins/hpsa-sudoers.erb

Hi,
I've create a check for HP Smart Array RAID controlers.

Added check hpsa for HP Smart Array RAID controlers

---

lib/facter/nagios_mdraid.rb
manifests/check/mdraid.pp
manifests/client.pp
manifests/server.pp
templates/plugins/check_mdraid

Hi.
I've create a check for Linux mdraid.

Add check_mdraid for Linux MD RAID.

---

templates/plugins/check_mptsas.erb

Edit to enable to catch more than one volume per controller for check_mptsas

Edit to enable to catch more volumes

---

files/pnp4nagios/common-header.ssi
manifests/pnp4nagios.pp
templates/apache_httpd/httpd-pnp4nagios.conf.erb

Based on your nagiosgraph class
Apache stuff hasn't been tested but should work as it's based on nagiosgraph

pnp4nagios class

---

README.md
manifests/server.pp

This change allows defining Nagios escalation rules.

Add host/service escalation rules support

---

templates/plugins/check_es_jvm_usage
templates/plugins/check_es_nodes
templates/plugins/check_es_unassigned_shards

Add default localhost to variable host for check_es_jvm_usage, check_es_nodes and check_es_unassigned_shards

Add localhost default to host variable to relevant plugin

---

README.md

README little typo

---

manifests/check/redis_sentinel.pp

puppet-lint change one " by '

---

manifests/check/http.pp
manifests/check/ipa_replication.pp
manifests/check/krb5.pp
manifests/check/zookeeper/key.pp
manifests/client.pp

Some little change (Puppet lint)

Puppet lint2

---

README.md
manifests/check/haproxy_stats.pp
manifests/client.pp
manifests/server.pp
templates/plugins/check_haproxy_stats

Add haproxy_stats nrpe check

---

manifests/server.pp
templates/plugins/README
templates/plugins/check_http_alt

Add alternative http check.
This pull request to replace the original one: 
edupr91: Add alternative http check. #168

Check http alt

---

manifests/server.pp
templates/plugins/README
templates/plugins/check_ssl_cert

Add check_ssl_cert because check_http miss CN verification and some certs checks

Add check_ssl_cert because check_http checks are not complete

---

manifests/check/krb5.pp

check_krb5: Change package name

---

templates/plugins/check_ssl_cert

plugins upgrade check_ssl_cert v1.140.0 -> v2.4.2

---

manifests/params.pp
templates/plugins/check_mongodb
templates/plugins/check_mongodb.orig

Updated checkmongo version to support Python3 and changes in params to use python3 and install python3-mongo as dependency from rhel8 or superior

Updated checkmongo version to support Python3 and changes in params 4 py3

---

lib/facter/nagios.rb
lib/facter/nagios_aerospike.rb
lib/facter/nagios_chproxy.rb
lib/facter/nagios_clickhouse.rb
lib/facter/nagios_consul.rb
lib/facter/nagios_couchbase.rb
lib/facter/nagios_dns.rb
lib/facter/nagios_elasticsearch.rb
lib/facter/nagios_fluentbit.rb
lib/facter/nagios_haproxy.rb
lib/facter/nagios_http.rb
lib/facter/nagios_ipa.rb
lib/facter/nagios_kafka.rb
lib/facter/nagios_mdraid.rb
lib/facter/nagios_memcached.rb
lib/facter/nagios_mongod.rb
lib/facter/nagios_moxi.rb
lib/facter/nagios_mysqld.rb
lib/facter/nagios_patroni.rb
lib/facter/nagios_postgres.rb
lib/facter/nagios_rabbitmq.rb
lib/facter/nagios_redis.rb
lib/facter/nagios_squid.rb
lib/facter/nagios_syncthing.rb
lib/facter/nagios_ups.rb
lib/facter/nagios_zookeeper.rb

Replaces all occurrences of `FileTest.` with `File.` in the fact ruby files.

Make facts Puppet 8 compatible

---

README.md
manifests/check/service.pp

Fix more legacy facts
