thias/puppet-nagios

- manifests/client.pp
- templates/nrpe.cfg.erb
All other settings in current template are parametrized.
I would like to have ability to set the debug through the class parameter, rather than hacking around.
> Allow setting debug parameter through nrpe.cfg template

- manifests/server.pp
- templates/nagios.cfg.erb
I needed to add `allow_empty_hostgroup_assignment=1` to the `nagios.cfg` configuration file, and I thought this would be a much better way to add additional nagios server parameters versus you having to deal with an un-ending barrage of pull requests adding each specific server parameters.
I didn't write any documentation in the README because there didn't seem like a good place to do that, but I certainly can if you want me to add that.
> Add cfg_append hash for nagios.cfg

- manifests/server.pp
This is a just a port of @alexharv074 suggested patch to properly allow
the user to manage the http configuration.
Issue: thias/puppet-nagios#31
> Decouple management of Apache virtual host

- manifests/server.pp
'resources' pseudo-resource is not 'changed', when actual resources are purged, so it can't notify service
record checksum of the config files instead and notify service if any of them changed
> restart service after resources are purged

- lib/facter/nagios_ipaddress6.rb
> Fix nagios_ipaddress6 fact to not throw an error if ipv6 not enabled

- manifests/check/postgres.pp
Syntax error at ':'; expected '}' at /etc/puppet/tvs-modules/nagios/manifests/check/postgres.pp:152
> Breaking this line in two seems to avoid a syntax error for me

- manifests/params.pp
- manifests/server.pp
- templates/nagios-4.cfg.erb
- templates/nagios-4.cfg.orig
Fixes CentOS 7 issue with nagios 4.0.8-2:
qh: Failed to init socket
'/var/log/nagios/rw/nagios.qh'. bind() failed: No such file or directory
> use nagios 4 original config for template

- manifests/check/mailq.pp
- manifests/server.pp
Since the package was already listed in this puppet module, it
looked like the intent was to have a mailq check.
> Add nagios::check::mailq

- README.md
- templates/plugins/slack_nagios
Nagios 4 has enable_environment_macros=0 which breaks the slack_nagios script, fixed by sending macros via arguments to the slack_nagios check.
> updated slack_nagios

- manifests/check/elasticsearch/mode.pp
fix elastichsearch typo in service_description, it is labeled correctly as elasticsearch everywhere else but it shows up in the interface as for example: "elastichsearch_cluster_status"
> correct elasticsearch typo in mode.pp

- templates/plugins/check_kafka_lag
* support for checing specific consumer lag
* send output of fail() function to stdout, so nrpe and nagios can pick
them up
> Changes to check_kafka_lag plugin:

- manifests/service.pp
recently added check_interval block has a typo resulting in puppetserver warnings
> fix check_interval typo

- manifests/client.pp
SELinux updates for RH8
avc:  denied  { map } for  pid=000000 comm="sudo" path="/usr/bin/sudo" dev="sda00" ino=0000000 scontext=system_u:system_r:nrpe_t:s0 tcontext=system_u:object_r:sudo_exec_t:s0 tclass=file permissive=0
> SELinux updates for RH8

- manifests/server.pp
- templates/nagios-4.cfg.erb
- templates/nagios.cfg.erb
Convenient function for just checking that a configuration is imported
and working correctly without shouting murder as soon as any firewall
issues and similar things are noticed upon deployment.
> Allow dis-/enabling notifications systemwide

- manifests/nagiosgraph.pp
So far, nagios::nagiosgraph tries to write everything to
`/usr/share/nagios/html`, which doesn't work with every packaging
system.
This makes this path configurable, and defaulting, of course, to
`/usr/share/nagios/html`.
This is similar to my other pull request for pnp4nagios.
> Make nagios_html_path a configurable option

- manifests/server.pp
Allow setting the `cfg_template` parameter in the `nagios::server` class, since overriding params with hiera is not very nice when using the role/profile model.
> Allow setting cfg_template manually

- manifests/server.pp
User may want or need to setup their mail server from outside the puppet module
This PR add this possibility
> making mailx installation optionnal

- README.md
- files/scripts/check_fluentbit_health
- lib/facter/nagios_fluentbit.rb
- manifests/check/fluentbit.pp
- manifests/client.pp
- manifests/server.pp
The Fluent Bit check uses the `/api/v1/health` endpoint to determine the health status of Fluent Bit.
The health check is performed by a custom script named `check_fluentbit_health`,
which is located by default at `/usr/lib64/nagios/plugins/`
This script checks the health of the Fluent Bit service by accessing the API endpoint `/api/v1/health`,
which provides health status directly from the Fluent Bit service.
By default, localhost and port 2020 are used for the check but you can customize it from hiera:
nagios::check::fluentbit::args: '-H your-fluentbit-host -p your-port-number'
> Fluentbit Check

- manifests/server.pp
- metadata.json
`validate_hash()` was removed from stdlib in version 9.0.0.  an alternative is to use puppet's built-in class parameter validation.
also add some entries to metadata.json because I'm successfully using the module with newer versions of puppet & RHEL/CentOS.
> stop using validate_hash(), refresh metadata.json

- manifests/check/haproxy_stats.pp
Updated the haproxy_stats manifest args to include --no-stats-exit-code 2
This ensures that failures to retrieve HAProxy stats are treated as critical (exitcode = 2) instead of unknown (exitcode = 3).
> Updated the haproxy_stats manifest args
